/* Scene — the trajectory.
 *
 *   τ = (s₁, a₁, r₁, s₂, a₂, r₂, …)  — a sequence of random variables.
 *
 *   Visual: a horizontal flow of triplet cards (state · action · reward),
 *   one card per turn, generated by sampling the environment. STEP adds
 *   one card; PLAY auto-advances; RESET starts a fresh battle.
 *
 *   No prose beyond a single line of caption at the bottom. The formula
 *   sits in a card above the flow.
 */
(function () {
  window.scenes = window.scenes || {};

  const NB = window.Battle.NUM_BUCKETS;
  const BUCKETS = window.Battle.BUCKETS;
  const ACTIONS = window.Moves.MOVE_IDS;

  function bucketName(b) { return b >= NB ? 'FAINT' : BUCKETS[b].toUpperCase(); }
  function bucketClass(b) {
    if (b === 0) return '';
    if (b === 1) return 'b1';
    if (b === 2) return 'b2';
    if (b === 3) return 'b3';
    return 'b4';
  }
  function bucketPct(b) { return Math.max(0, (NB - b) * 100 / NB); }
  function moveName(id) { return window.Moves.MOVE_BY_ID[id].name; }

  /* Render one (s, a, r) tuple as a card. `step` is the i-index; `s` is
     the *pre-action* state; `aId` is the action just taken; `r` is the
     resulting reward; `terminal` flags whether this card ends the run. */
  function renderTuple(host, step, s, aId, r, terminal, won) {
    const card = document.createElement('div');
    card.className = 'traj-tuple';
    if (terminal) {
      card.classList.add('terminal');
      if (!won) card.classList.add('loss');
    }
    const yourBucket = s.your === undefined ? 0 : s.your;
    const oppBucket  = s.opp  === undefined ? 0 : s.opp;
    const rewardClass = r > 0 ? 'pos' : (r < 0 ? 'neg' : 'neutral');
    const rewardSign  = r >= 0 ? '+' : '';

    /* Redundant icon channel for colour-blind safety: ✓ on win, ✗ on
       loss. Pairs with the blue/vermillion terminal background so
       either channel alone tells the outcome. */
    let termIcon = '';
    if (terminal) termIcon = won ? ' ✓ WIN' : ' ✗ LOSS';

    card.innerHTML =
      '<div class="traj-tuple-step">i = ' + step + termIcon + '</div>' +
      '<div class="traj-tuple-state">' +
        '<div class="traj-tuple-side">' +
          '<img class="traj-tuple-sprite" src="assets/pikachu-back.png" alt="">' +
          '<div class="traj-tuple-hp"><div class="traj-tuple-hp-fill ' + bucketClass(yourBucket) + '" style="width:' + bucketPct(yourBucket) + '%"></div></div>' +
          '<div>' + bucketName(yourBucket) + '</div>' +
        '</div>' +
        '<div class="traj-tuple-side">' +
          '<img class="traj-tuple-sprite" src="assets/charmander-front.png" alt="">' +
          '<div class="traj-tuple-hp"><div class="traj-tuple-hp-fill ' + bucketClass(oppBucket) + '" style="width:' + bucketPct(oppBucket) + '%"></div></div>' +
          '<div>' + bucketName(oppBucket) + '</div>' +
        '</div>' +
      '</div>' +
      '<div class="traj-tuple-action">aᵢ = ' + (aId ? moveName(aId) : '—') + '</div>' +
      '<div class="traj-tuple-reward ' + rewardClass + '">rᵢ = ' + rewardSign + r + '</div>';

    host.appendChild(card);
    /* Scroll into view so the latest tuple is always visible. */
    setTimeout(() => host.scrollLeft = host.scrollWidth, 30);
  }

  window.scenes.sceneTrajectory = function (root) {
    root.classList.add('scene-pad', 'concept-scene');
    root.innerHTML = '';

    const heading = document.createElement('h2');
    heading.className = 'concept-heading';
    heading.textContent = 'THE TRAJECTORY';
    root.appendChild(heading);

    /* Formula card */
    const fcard = document.createElement('div');
    fcard.className = 'concept-formula-card';
    fcard.innerHTML = '<div class="concept-formula-label">TRAJECTORY (RANDOM VARIABLES)</div>';
    const fhost = document.createElement('div');
    fcard.appendChild(fhost);
    window.Katex.render(
      String.raw`\tau = (s_1, a_1, r_1, \; s_2, a_2, r_2, \; s_3, a_3, r_3, \; \dots)`,
      fhost, true
    );
    const ffoot = document.createElement('div');
    ffoot.className = 'concept-formula-foot';
    ffoot.textContent = 'sᵢ = state · aᵢ = PIKACHU\'s move · rᵢ = reward · sᵢ₊₁ = state AFTER aᵢ';
    fcard.appendChild(ffoot);
    root.appendChild(fcard);

    /* Rollout panel */
    const rollout = document.createElement('div');
    rollout.className = 'traj-rollout';
    root.appendChild(rollout);

    /* Controls */
    const ctrls = document.createElement('div');
    ctrls.className = 'traj-controls';
    ctrls.innerHTML =
      '<button class="poke-btn" id="traj-step">▶ NEXT TURN</button>' +
      '<button class="poke-btn" id="traj-play">▶▶ PLAY</button>' +
      '<button class="poke-btn" id="traj-reset">RESET</button>' +
      '<div class="traj-status">step <b id="traj-status-i">0</b> · <span id="traj-status-state">FULL / FULL</span></div>';
    root.appendChild(ctrls);

    /* ---- State ---- */
    let rng = window.Battle.makeRng(0x1234);
    let s = window.Battle.initialState();
    let stepIdx = 1;
    let done = false;
    let playTimer = null;

    function reset() {
      stopPlay();
      rng = window.Battle.makeRng(0x1234 + Math.floor(Math.random() * 65535));
      s = window.Battle.initialState();
      stepIdx = 1;
      done = false;
      rollout.innerHTML = '';
      updateStatus();
    }

    function stopPlay() {
      if (playTimer) { clearInterval(playTimer); playTimer = null; }
    }

    function nextTurn() {
      if (done) { reset(); return; }
      /* Random uniform action — this scene is about the trajectory, not
         the policy. ε=1 effectively. */
      const aIdx = Math.floor(rng() * ACTIONS.length);
      const aId  = ACTIONS[aIdx];
      const sBefore = { your: s.your, opp: s.opp };
      const out = window.Battle.sample(s, aId, rng);
      renderTuple(rollout, stepIdx, sBefore, aId, out.reward, out.terminal, out.win);
      stepIdx++;
      if (out.terminal) {
        done = true;
      } else {
        s = out.sNext;
      }
      updateStatus();
    }

    function updateStatus() {
      document.getElementById('traj-status-i').textContent = String(stepIdx - 1);
      const stateEl = document.getElementById('traj-status-state');
      if (done) {
        stateEl.textContent = 'EPISODE OVER';
      } else {
        stateEl.textContent = bucketName(s.your) + ' / ' + bucketName(s.opp);
      }
    }

    function play() {
      stopPlay();
      playTimer = setInterval(() => {
        nextTurn();
        if (done) stopPlay();
      }, 650);
    }

    document.getElementById('traj-step').addEventListener('click', nextTurn);
    document.getElementById('traj-play').addEventListener('click', play);
    document.getElementById('traj-reset').addEventListener('click', reset);

    updateStatus();

    /* &run: auto-play for headless screenshots. */
    const autoRun = /[#&?]run\b/.test(window.location.hash);
    if (autoRun) setTimeout(play, 200);

    return {
      onEnter() { updateStatus(); },
      onLeave() { stopPlay(); },
    };
  };
})();
